# Generated by Django 5.2.8 on 2025-11-11 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de Dispositivo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo Específico')),
                ('serial', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie/Inventario')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
            ],
            options={
                'verbose_name': 'Dispositivo Tecnológico',
                'verbose_name_plural': 'Dispositivos Tecnológicos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Marca')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o Fabricante')),
            ],
            options={
                'verbose_name': 'Marca de Dispositivo',
                'verbose_name_plural': 'Marcas de Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres del Empleado')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos del Empleado')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento o Área')),
                ('cedula_empleado', models.CharField(max_length=10, unique=True, verbose_name='Cédula de Empleado')),
            ],
            options={
                'verbose_name': 'Usuario de Equipo',
                'verbose_name_plural': 'Usuarios de Equipos',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('tipo', models.CharField(choices=[('P', 'Preventivo'), ('C', 'Correctivo')], max_length=50, verbose_name='Tipo de Mantenimiento')),
                ('descripcion_trabajo', models.TextField(verbose_name='Trabajo Realizado')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo del Mantenimiento')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo', verbose_name='Dispositivo Afectado')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimientos',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca', verbose_name='Marca'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de Asignación')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.dispositivo', verbose_name='Dispositivo Asignado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.usuario', verbose_name='Empleado Asignado')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Asignaciones de Equipos',
            },
        ),
    ]
